version: '3.8'
services:
  mongo1:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip localhost,mongo1 --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip localhost,mongo2 --port 27017
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip localhost,mongo3 --port 27017
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
